/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        beige: { DEFAULT: "#fffbf0", deep: "#f3ecd9" },
        corail: { DEFAULT: "#ff6f62", soft: "#ff8a7f", dark: "#e85b4f" },
        marine: { DEFAULT: "#061a2d", soft: "#0e2c47" },
        turquoise: { DEFAULT: "#061a2d", vivid: "#ff6f62" },
        teal: { deep: "#061a2d" },
        creole: { DEFAULT: "#ff6f62", soft: "#ff8a7f" },
        sand: "#f3ecd9",
        cream: "#fffbf0",
        ink: "#061a2d",
        background: "#ebe8e0",
        foreground: "#343833",
        card: "#faf9f9",
        "card-foreground": "#343833",
        popover: "#ffffff",
        "popover-foreground": "#343833",
        primary: "#4e332d",
        "primary-foreground": "#ebe8e0",
        secondary: "#f2efe7",
        "secondary-foreground": "#4e332d",
        muted: "#efede5",
        "muted-foreground": "#767470",
        accent: "#0e301a",
        "accent-foreground": "#ebe8e0",
        border: "#d7d1c6",
        input: "#d7d1c6",
        ring: "#9a5636",
        linen: "#ebe8e0",
        paper: "#faf9f9",
        snow: "#ffffff",
        forest: "#0e301a",
        smoke: "#343833",
        copper: "#9a5636",
        umber: "#4e332d",
        oxblood: "#69253a",
      },
      fontFamily: {
        display: ['"UC Desert Rain"', '"Instrument Serif"', "ui-serif", "Georgia", "serif"],
        body: ['"Urbanist"', "ui-sans-serif", "system-ui", "sans-serif"],
        brand: ['"UC Brothers"', '"Arial Narrow"', "sans-serif"],
        label: ['"UC Brothers"', '"Arial Narrow"', "sans-serif"],
        button: ['"UC Brothers"', '"Arial Narrow"', "sans-serif"],
        topic: ['"UC Bianco Sans"', "ui-sans-serif", "system-ui", "sans-serif"],
        brothers: ['"UC Brothers"', '"Arial Narrow"', "sans-serif"],
        desert: ['"UC Desert Rain"', "Georgia", "serif"],
        uchen: ['"UC Arvo"', "Georgia", "serif"],
        urbanist: ['"Urbanist"', "ui-sans-serif", "system-ui", "sans-serif"],
      },
      boxShadow: {
        card: "0 10px 40px -12px rgba(6, 26, 45, 0.18)",
        float: "0 24px 60px -20px rgba(6, 26, 45, 0.38)",
      },
      borderRadius: {
        xl2: "1.25rem",
      },
      backgroundImage: {
        "hero-fade":
          "linear-gradient(180deg, rgba(6,26,45,0.15) 0%, rgba(6,26,45,0.55) 55%, rgba(6,26,45,0.9) 100%)",
      },
      keyframes: {
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "scale-in": {
          "0%": { opacity: "0", transform: "scale(0.97)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
      },
      animation: {
        "fade-in": "fade-in 0.4s ease-out both",
        "scale-in": "scale-in 0.25s ease-out both",
      },
    },
  },
  plugins: [],
};
